name: Documentazione
run-name: Publishing docs
on:
    push
jobs:
    build-documentation:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.11']
        steps:
            - uses: actions/checkout@v4
            - name: Update ubuntu
              run: |
                  sudo apt-get update
                  sudo apt-get install -y
            - name: Install pdflatex
              run: |
                sudo apt-get install -y texlive-latex-base
                sudo apt-get install -y texlive-lang-italian
                sudo apt-get install -y texlive-fonts-recommended
                sudo apt-get install -y texlive-latex-extra
                sudo apt-get install -y texlive-science
                
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Build pdf
              run: python3 scripts/build.py -o docs -s PB
            - name: Publish artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Documentazione-${{ github.ref_name }}
                  path: |
                      docs

